#+BLOG: wurly-blog
#+POSTID: 1136
#+ORG2BLOG:
#+DATE: [2024-02-18 Sun 14:59]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: 
#+TAGS: 
#+DESCRIPTION:
#+TITLE: iPhoneでIIJmioの音声eSIMと他社またはIIJmioのSIMカードもしくはeSIMを併用

* はじめに

数ヶ月前に、ヨーロッパに海外出張に行ったのですが、その際のmobile回線をどのように使用したか、という話です。

iPhone 13mini にて、主回線はIIJmio(Docomoタイプ)を使っているのですが、まずこれをeSIMに変更し、その上でプリペイド式のSIMカードを副回線としてセットする方式を取りました。

こうすることで、各種認証等は主回線のものを使用しながら、海外のmobile回線を使用することができます。

ただ、この構成だと主副ともにMVNOタイプとなるため、注意が必要でした。

* 内容

#+begin_quote
​​【注意事項】​​
​​・APN構成プロファイルは、iPhone端末1台につき1つしかインストールできません。​​そのため、モバイルデータ通信に利用するSIMを切り替える際、​都度APN構成プロファイルの削除とインストールが必要​です。
#+end_quote

上記の通り、今回の構成では、主副の回線を切り替える際に、APN構成プロファイルの削除とインストールが必要​となります。
面倒ですが、今回の私のケースでは、海外において使用する間、併用するSIMカードのみを使い、IIJmioの方は使わないのでそれほど問題にはなりませんでした。

IIJmioのAPN構成プロファイルは通常、WiFi環境可でダウンロードしてインストールする必要がありますが、
出発前に iPhone アプリの「ファイル」に保存しておけば、オフラインでAPN構成プロファイルがインストールできます。
実際、帰国時に「ファイル」アプリからAPN構成プロファイルをインストールすることで帰国してすぐにIIJmioを使うことができました。

* 参考
 - [[https://help.iijmio.jp/answer/634f990456218b7e2cb795bb/][［iPhone］IIJmioの音声eSIMと他社またはIIJmioのSIMカードもしくはeSIMを併用することは出来ますか？【eSIM】 : IIJmio Q&A]]

* おわりに
