#+BLOG: wurly-blog
#+POSTID: 1650
#+ORG2BLOG:
#+DATE: [2024-11-04 Mon 22:09]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: WordPress
#+TAGS: 
#+DESCRIPTION:
#+TITLE: niftyホームページサービス(LaCoocan)からXServerレンタルサーバーへ引っ越し

* はじめに

様々な理由により、ブログをniftyホームページサービス(LaCoocan)からXServerレンタルサーバーへ引っ越すことにしました。
LaCoocanは長年使用してきました。過去のメールを確認したところ、なんと、2007年1月から18年近く利用していることになります。

* XServerについて

XServerについては以前から知っていました。
LaCoocanを契約した時点でも知っていたと思います。niftyと比べると専門的な印象で価格が高く、その時点ではまだ新興のサービスだったので信頼度が未知数だったため、niftyを選んだという記憶があります。
今や、XServerもサービス開始から21年となるようで老舗と言っていいと思います。
2024年10月時点、W3Techs 調べで、国内シェアNo.1とのこと。
実績から見れば安心して使用できると思いました。

* XServerのお友達紹介プログラム

結論から言いますと、お友達紹介プログラムを利用するとお得なので、利用しない手はないかと思います。
キャンペーン特典と併用できます。
下記リンクから利用できます。

 - [[https://www.xserver.ne.jp/?referral_token=4038223236728c81e922ba][お友達紹介プログラム(XServerレンタルサーバー)]]

実は、最初、私はこれを知らず、通常のキャンペーン特典(最大30%OFF)にて申込みを行い、10日間のお試しを開始していました。
管理画面等の確認をし、問題がなさそうであるということを確認、「独自ドメイン永久無料特典」を利用するために支払いをしようとして契約期間を検討していたところでした。
そこでいろいろと調べていたところ、お友達紹介プログラムにより5000円または10000円の割引になるということを知り、当初申し込んだ方をキャンセルし、新たにキャンペーンリンクから申し込むことで、キャンペーンが適用されました！

* 契約期間について

契約期間は、特典や割引率を考慮して1年以上というところに迷いはありませんでしたが、2年/3年を選択するかどうか、迷いました。

継続時には割引はなく、その場合2年、3年契約での割引率は、あまり高くないのですが、初回契約で、キャンペーン(30%OFF)＋10000円の割引金額はかなり大きいです。
もちろん3年分なのでその分、割引金額が多いのですが、通常35,640円のところ、30%OFFで-10,692円、お友達紹介プログラムで-10,000円ということで、14,948円となります。
割引なし(契約継続の場合)の1年契約(1,100円/月)が13,200円ということを考えますと、通常約1年分の金額で3年使えるということになります。

3年という長期契約は通常であればかなり抵抗感があります。
もちろん、このあたりの考え方は個人の事情によりますが、私の場合は細々とではありますが20年以上ブログをやっておりコンテンツがそれなりにあり、当面やめようということは考えておりません。
その前提でキャンペーン＋お友達紹介プログラム適用で、通常の約1年分の金額で使用できるということであれば(もし仮に1年で使わなくなったとしても約1年分の費用にしかならないわけで)損することにはならないと考え、3年契約としました。

* 契約の更新について

最後に気になったところは、最初に3年契約してしまうと、次回更新時にも3年契約が必須となるのか？ということだったのですが、そういった縛りはなく、少なくとも2024年11月4日時点では自動更新サイクルは変更可能でした。
私の場合は、念の為、3年分の支払後、自動更新サイクルを「1年ごとに更新」に変更しておきました。
(いざ更新の際には3年を選択するかもしれません)

* 私の利用プラン

今回の移行の一番の目的は、ドメインを取得しTLS(https)接続に変更することです。
前々からTLS非対応であることを気になってはいたのですが、サーバー移行が伴うため、なかなか着手できてきませんでした。
最近、私自身、TLS接続でないウェブサイトにはアクセスするべきではないと考えたことで、自分が運用するサイトについてもTLSに対応することを決断しました。

私としてはドメインはXServer独自(Let's Encrypt)で十分信頼に値すると考えており、「独自ドメイン永久無料特典」を使用します。よって1年以上の契約が必要となります。

2年以上の契約ですと、ドメインは2つ取得できるのですが、実際には https://www.xserver.ne.jp/manual/man_order_present_domain.php に記載がある通り、2つ目は .blog / .online / .site に限られ、移管もできないのであまり意味がありません。

独自ドメインは、安定の .com ドメインを取得しました。
なお、当初希望していたとても短く簡潔な名前(wurly)は、私には馴染みのない .xyz ドメインについては空きがあり、少し調べてみたところ将来性はあるドメインだと思いました。
が、現時点では一般の人には不審なものとして判断されかねないと判断し、ブログ以外にドメインを使用することも想定し、複数の目的を束ねるという意味を込めて "hub" を付与した wurlyhub.com を取得しました。
ブログについては blog. サブドメインで管理することにしました。

WordPressについては、「WordPress簡単移行」を使用しました。画像のパスなど、URL直書きしていた部分についてはいくつか修正が必要でしたが、問題なく移行できました。
それなりに時間がかかることを想像していましたが、1時間かかったかかからないくらいであっさり完了しました。

* おわりに

ずっと気になっていたTLS化が完了してとても嬉しいです。
初回契約については、お友達紹介プログラムを見つけることができ、かなりお得な料金で申込みできました。
ページの読み込み速度もかなり早くなったのでアクセス数の増加を期待しています。

なお、LaCoocanの方は1年契約で次の更新まで数ヶ月なので、この間にWordPress以外の残りのコンテンツをXServerに移動予定です。
