#+BLOG: wurly-blog
#+POSTID: 568
#+ORG2BLOG:
#+DATE: [2023-08-11 Fri 16:15]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: PC
#+TAGS: 
#+DESCRIPTION:
#+TITLE: 自作デスクトップPC パーツ変更検討

* 概要

現在、メインのPCはラップトップになり、以前使用していた自作デスクトップPCはサブ用途となっています。
こちらは、機械学習などのキャッチアップ用に別途グラフィックボードの変更を検討しているのですが、ベースが古い為、パーツ変更の検討を始めます。

* 方向性

ヤフオク(中古)で Intel Core i7-10700 又は i7-10700F を含む、マザーボード、メモリーのセットを購入することを狙いたいと思います。

* 詳細

** 参考

下記ページの数値を用いて検討しています。

 - [[https://btopc-minikan.com/cpu-hikaku.html][CPUベンチマークと性能比較【2023年最新版】 | BTOパソコンミニ館]]
https://btopc-minikan.com/cpu-hikaku.html

** CPU

現在使っているものは、Core i7-6700T(4C8T) 8879 です。

最近私が考えた指標は、ベンチマークの数値で約2倍となるようなものを選ぶということです。

何か購入するとき、それが本当に必要なのかという判断をする場合、2倍という数値は私にはリーズナブルであるという印象を受けるからです。

なお、現在使用しているメインPCは、Core i5-1235U(10C12T) 13589 でこの指標を用いた、、つもりでしたが約1.5倍にしかなっていないですね。
(この時はデスクトップからラップトップへの移行もありましたので、これを考慮しました。)

というわけで、Core i7-10700(8C16T) 17614、Core i7-10700F 16034 (65W)を一旦ターゲットとします。

Kシリーズ(19761,125W)は電源効率が悪いので対象から除外します。
本当は現在と同じくTシリーズ(13047,35W)が理想ですが、入手性とコストパフォーマンスを考慮してこちらも一旦除外します。

その他の候補として、i5-11600(6C12T) 18058、i5-11500(6C12T) 17895、i5-11400(6C12T) 17502 あたりとなります。
ただ、世代的に新しいので割高になること、i5はラインナップが複数ありヤフオク上の商品の選定に手間がかかること、
用途上 6C12T よりも 8C16T の方が好ましいと考えました。

** その他

ヤフオクで購入する際のポイントとして、セット(CPU、マザーボード、メモリー等)の方が安く購入できる可能性が高いです。
出品数は単品の場合よりも少なくなりますが、用途が限定される分、購入を希望する人が減るので、価格が下がる傾向があります。
一方で、CPU以外のパーツを含めた希望の構成の商品が出品されるかはわかりません。根気強く待つ必要があるかもしれません。

これを踏まえますと、もし売りたい場合には単品で出品する方がよいです。合計金額が多くなる傾向があります。

上記は、私が何度か出品、落札をした経験に基づきます。

なぜ、損をするにも関わらず、セット(CPU、マザーボード、メモリー等)で出品する人がいるのかと言いますと、出品が面倒であるからであると思われます。

これも私が出品した際の経験に基づきます。できれば手間をかけずにセットで高く売りたいところですが、なかなか上手くいきません。

よって、原則としては「売る場合には単品」、「買う場合にはセット」がリーズナブルであると言えると思います。
