#+BLOG: wurly-blog
#+POSTID: 327
#+ORG2BLOG:
#+DATE: [2023-04-29 Sat 18:35]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: WordPress
#+TAGS: 
#+DESCRIPTION:
#+TITLE: WordPress の見た目など

* 概要

最近はできるだけWordPressのサイトに投稿したいと考えています。
そんな中、これまでほぼデフォルト設定のままにしていた見た目が気になってきました。
下記のような点です。

 - アイキャッチ画像が NO IMAGE になっている
 - 背景が白背景のまま
 - ヘッダー、フッターが白背景、黒文字のまま
 - サイトについての説明が無い

* アイキャッチ画像の設定

ChatGPT先生に聞いてみたところ、ロイヤリティフリーの画像を使用するアドバイスと、下記サイトの紹介をもらいました。

 - Unsplash https://unsplash.com/ 多様なジャンルの高品質な写真が豊富にそろっています。
 - Pexels https://www.pexels.com/ 商用利用も可能な高品質な写真が数多く用意されています。
 - Pixabay https://pixabay.com/ 商用利用も可能なフリー画像が多数あり、高品質なイラストやベクター画像もそろっています。
 - Kaboompics https://kaboompics.com/ ファッションやインテリアなどのライフスタイル系の写真が中心で、美しい色合いや光の使い方が特徴的です。
 - Gratisography https://gratisography.com/ 独創的でユニークな写真が豊富にそろっています。商用利用も可能です。

まずは、汎用的な画像をデフォルトとして設定したいと思いました。

Unsplash から青空の画像をもらって設定したのですが、しっくり来ません。

再びUnsplashで画像を探していたところ、いくつかPCが置かれた写真があり、これまでサイトを見た経験も踏まえ、これなら汎用的に使えそうです。

ただそれならば自分のPCを撮ってしまえ、ということで一発撮ってみたところ割りと良い感じなのでこれを採用します。

(たまたま、外部ディスプレイを繋げていて内蔵ディスプレイはOFFにしていたのですがむしろこれがよい)

Cocoon の場合は、「Cocoon 設定」 → 「画像」から、NO IMAGE設定 でデフォルトとして設定できました。

 - [[https://yoshitechblog.com/cocoon-original-no-image][【NO IMAGE】アイキャッチをオリジナル画像にする｜WordPress・Cocoon]]
https://yoshitechblog.com/cocoon-original-no-image

* 背景、ヘッダー、フッターの設定

背景画像は、「外観」→「背景」から設定しました。上下方向に連続的に繋がるものを選びました。

ヘッダーについては、「Cocoon 設定」 → 「ヘッダー」から、画像と文字色を設定しました。

フッターについては、「Cocoon 設定」 → 「フッター」から、背景色と文字色を設定しました。

* サイトについての説明

「固定ページ」から固定ページを作成します。

これだけだと作成したページはどこにも表示されないので、「設定」→「表示設定」から、「ホームページの表示」で「固定ページ」を選び、作成したページを「ホームページ」として指定しました。

 - [[https://www.hiyaman-blog.com/cocoon_toppage_customize/][【Cocoon】固定ページを使ってブログのトップページをサイト型表示にする方法【WordPress】 - ひやまんブログ]]
https://www.hiyaman-blog.com/cocoon_toppage_customize/

* その他

「外観」→「ウィジェット」からサイドバーに「カレンダー」「プロフィール」を追加しました。
「検索」「最近の投稿」「プロフィール」「カテゴリー」「カレンダー」「アーカイブ」「メタ情報」の順に並び替えました。
スパムがひどく既にコメントはできない設定にしているので、「最近のコメント」は削除しました。

「ユーザー」の「プロフィール情報」を入力しました。

# アピールエリアも設定しました。
# 「アピールエリアの表示」を「表示しない」→「全ページで表示」
# これは違う


* 結果

個人的にはだいぶ改善したと考えています。
特に、自分で見た場合でもアイキャッチ画像が NO IMAGE になっているのは非常に印象が悪いので、これがデフォルト画像として設定できたのは非常に良かったです。
