#+BLOG: wurly-blog
#+POSTID: 677
#+ORG2BLOG:
#+DATE: [2023-09-18 月 14:08]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: Ubuntu
#+TAGS: 
#+DESCRIPTION:
#+TITLE: Ubuntu 22.04 Ctrl + ; のショートカットの無効化

* 概要

Ubuntu 22.04 では Ctrl + ; が何らかの機能(ショートカット)に割り当てられています。

ただ、私はEmacs上で別の機能として使っているため、これを無効化します。

そもそも、これがどういった機能であるかも不明であったため、機能と変更方法を調べました。

下記の投稿の続きとも言える内容です。

- [[./?p=471][WSL2 Mozc カスタマイズ]]

* 結論

Ctrl + ; は、ibus-mozc における絵文字入力のショートカットキーでした。

(使い方としては、このショートカットキーを入力すると e という文字が出ますので、その状態で "smile"などと入力し、スペースキーを押すと所定の絵文字に変換されます。)

下記コマンドで設定が変更できます。「絵文字」のタブです。

#+begin_src sh
$ ibus-setup
#+end_src

既定では Ctrl + . (ピリオド) と Ctrl + ; (セミコロン) が割り当てられています。

file:./images/677_01.png

# file:./images/677_02.png

Ctrl + ] (四角括弧閉じ)を割り当てました。

file:./images/677_03.png

* ibus-mozc と fcitx-mozc について

下記は、今回の調査の中で理解したこと、試したことです。

 - [[https://www.linux-setting.tokyo/2023/04/linuxibus-mozc-vs-fcitx-mozcibus.html][Linuxの日本語入力環境　ibus-mozc v.s. fcitx-mozc：基本中の基本・・ibus-mozcとfcitx-mozcの徹底的な違いって何？]]
https://www.linux-setting.tokyo/2023/04/linuxibus-mozc-vs-fcitx-mozcibus.html

上記によると、ibus-mozcとfcitx-mozcはLinuxの日本語入力環境として使用されるものであり、fcitx-mozcの方がアプリケーションウィンドウ毎にで日本語入力のOn/Offの状態を持つことが可能である点で使いやすいとのことです。

なお、Ubuntu 22.04 LTS 日本語 Remix版をインストールした際の既定は ibus-mozc でした。

 - [[https://hirooka.pro/ubuntu-22-04-lts-japanese-input-ibus-fcitx-mozc/][Ubuntu 22.04 LTSで日本語入力 (iBus – Mozc, Fcitx – Mozc)│hirooka.pro]]
https://hirooka.pro/ubuntu-22-04-lts-japanese-input-ibus-fcitx-mozc/

上記には、ibus-mozc と fcitx-mozc それぞれへの切り替え方法、設定方法が説明されています。

当初、fcitx-mocz の方が使いやすいとのことで、そちらをインストールして切り替えたところ、確かに高機能なように見えました。
ただ、既定ではUSキーボードの設定となっており、それからJPキーボードへの切り替え方法に苦戦したため、ibus-moczに戻し、こちらを使うことにしました。

なお、ibus-mozc と fcitx-mozc は 地域と言語(Region & Language) → インストールされている言語の管理(Manage Installed Languages) のところ、
または "imconfig -n ibus" "imconfig -n fcitx5" のようなコマンドで切り替えられますが、両方インストールしているとうまく動かないことがあるため、使わないものについては削除した方がよさそうです。

* 参考

** ibus
 - [[https://wiki.archlinux.jp/index.php/IBus][IBus - ArchWiki]]
 - [[https://www.yokoweb.net/2022/06/30/ubuntu-emoji-ibus-setup/][Ubuntu 22.04 Desktopで、CTRL+. の絵文字ショートカットキーを変更 | The modern stone age.]]

** fcitx
 - [[https://notekunst.hatenablog.com/entry/fcitx-mozc][日本語入力の設定（fcitx + mozc） - Note to Self by notekunst]]
 - [[https://wiki.archlinux.jp/index.php/Fcitx5][Fcitx5 - ArchWiki]]
 - [[https://forums.ubuntulinux.jp/viewtopic.php?id=21498][Ubuntu日本語フォーラム / fcitxが自動で起動しません]]
 - [[https://pc.shigizemi.com/2018/04/08/ubuntu%e3%81%aelibreoffice%e3%81%aecalc%e3%81%a7%e6%97%a5%e4%bb%98%e3%82%92%e3%80%8cctl%e3%80%8d%e3%81%a7%e5%85%a5%e5%8a%9b/][UbuntuのLibreOfficeのcalcで「Ctl+;」が使えない | Ubuntu | 福岡県パソコンサポート|志義どっとPC]]

# ./images/677_01.png http://cha.la.coocan.jp/wp/wp-content/uploads/2023/09/677_01.png
# ./images/677_02.png http://cha.la.coocan.jp/wp/wp-content/uploads/2023/09/677_02.png

# ./images/677_03.png http://cha.la.coocan.jp/wp/wp-content/uploads/2023/09/677_03.png
