#+BLOG: wurly-blog
#+POSTID: 866
#+ORG2BLOG:
#+DATE: [2023-11-25 土 08:35]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
#+CATEGORY: WSL, Ubuntu
#+TAGS: 
#+DESCRIPTION:
#+TITLE: Ubuntu 日本語 Input Method の設定 (fcitx-mozc)

* 概要

WSL上のUbuntuを使い始めてしばらくは、fcitx-mozcの設定が上手く行かなかったので、日本語入力はEmacs上でしか行っていませんでした。
そちらでは日本語変換の品質が低いので、やはりmozcを使いたくなりました。

Emacs上だけmozcを使うこともできそうですが、Chromeなどでもできれば使いたいので、IM(Input Method)で使えるようにします。

日本語 Remix では ibus-mozc が採用されていますが、いろいろトライしてみてもWSL上では動作しなかったので、fcitx-mozc を使うことにしました。

[[./?p=873][Ubuntu IM (Input Method)、特にfcitxとibusについて]] もご覧ください。

現時点では、下記に記載した内容は、どれが必須で、どの順番で行えばよいのかを確定できていません。

トライ＆エラーで何度か実行することで、使用できるようになりました。

* 日本語 Remixに追加されているパッケージをインストール

 - [[https://www.ubuntulinux.jp/japanese][Ubuntuの日本語環境 | Ubuntu Japanese Team]]

Ubuntu 22.04 の場合

#+begin_src bash
sudo wget https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -P /etc/apt/trusted.gpg.d/
sudo wget https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -P /etc/apt/trusted.gpg.d/
sudo wget https://www.ubuntulinux.jp/sources.list.d/jammy.list -O /etc/apt/sources.list.d/ubuntu-ja.list
sudo apt update
#+end_src

#+begin_src bash
$ sudo apt-get install ubuntu-defaults-ja
#+end_src

* 日本語言語パックのインストール

#+begin_src 
$ sudo apt -y install language-pack-ja
#+end_src

* Windowsの日本語フォントを使用する設定

#+begin_src sh
$ cat << 'EOS' | sudo tee /etc/fonts/local.conf
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>/mnt/c/Windows/Fonts</dir>
</fontconfig>
<!-- Created by bash script from https://astherier.com/blog/2021/07/windows11-wsl2-wslg-japanese/ -->
EOS
#+end_src

* キーボードを日本語配列にする

日本語関連設定が何もされていない場合、下記のようになっているはずです。

#+begin_src
$ localectl
   System Locale: LANG=C.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
#+end_src

jp106 に設定します。

#+begin_src bash
$ sudo localectl set-x11-keymap jp jp106
$ localectl
   System local: LANG=C.UTF-8
       VC keymap: jp106
     x11 Layout: jp
       x11 Model: jp106
#+end_src

** 参考
 - [[https://tkyonezu.com/os-linux-windows/ubuntu-server-20-04%E3%82%92%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%8C%96%E3%81%99%E3%82%8B/][Ubuntu Server 20.04を日本語化する | Takeshi Yonezu]]

* ロケール

** 日本語ロケールの追加

下記を実行し、ja_JP.UTF-8 をマークすることで、日本語ロケールがインストールできます。

最後にシステムロケールの選択ができます。

#+begin_src bash
$ sudo dpkg-reconfigure locales
#+end_src

システム上のメッセージ(マニュアル、エラーなど)を全て日本語にしたい場合には、システムロケールは Ja_JP.UTF8 にするのが良いと思います。
私は、英語のままがよいので C.UTF-8 にしています。

** システムロケールの選択

コマンドで行う場合には下記のように設定できます。

#+begin_src bash
$ sudo update-locale LANG=C.UTF8
#+end_src

#+begin_src bash
$ sudo update-locale LANG=ja_JP.UTF8
#+end_src

** 参考
下記を参考にしました。

 - [[https://scratchpad.jp/ubuntu-on-windows11-2/#toc4][UbuntuをWindows11上で動かす その2: 環境の整備 | メモ置場のブログ]]
https://scratchpad.jp/ubuntu-on-windows11-2/#toc4

* fcitx-mozc のインストール

#+begin_src bash
$ sudo apt install fcitx-mozc
#+end_src

* fcitx-mozc の設定

~/.profile に下記を追記します。

#+begin_src bash
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export DefaultIMModule=fcitx
if [ $SHLVL = 1 ] ; then
    fcitx-autostart > /dev/null 2>&1
    xset -r 49
fi
#+end_src

* im-config

#+begin_src bash
$ im-config&
#+end_src

fcitx を選択します。

file:images/873_01.jpg

file:images/873_02.jpg

file:images/873_03.jpg

file:images/873_04.jpg

file:images/873_05.jpg

* fcitx-config-gtk3

#+begin_src bash
$ fcitx-config-gtk3&
#+end_src

 - Input Method のタブで Mozc を追加します。
 - また、ここで一番上が 「Keyboard - English (US)」 (「キーボード - 英語 (US)」)になっている場合は、これを削除し、新たに 「Keyboard - japanese」(「キーボード - 日本語」)を追加し、一番上になるように移動します。
 - 全角/半角 キーで Mozc へ切り替える場合
  - Global Config のところで Trigger Input Method のところを Zenkakuhankaku に設定します。
  - Extra key for trigger input method は Disable にします。
 - ショートカットの設定変更
  - [[./?p=471][Ubuntu 22.04 Ctrl + ; のショートカットの無効化 (fcitx-mozc)]]
 - インライン入力の設定
  - [[https://dev.to/nabbisen/fcitx--1n59][Fcitx: リアルタイム入力（インライン入力）のための設定 - DEV Community]]
  - 私の環境ではインライン入力ができておらず、日本語入力が別ウィンドウで行われる状態です。上記を参考にインライン入力の設定はできたのですが、表示は変わらずでした。

* gnome-tweaks

gnome-tweaks で Gnome の設定を開くことができます。

#+begin_src bash
apt install gnome-tweaks
#+end_src

キーボード設定など、ここから設定できるものもあるかもしれません。

* dpkg-reconfigure keyboard-configuration

コンソールで使うキーボードレイアウトの設定ができるようですが、WSLからだと下記のメッセージが表示され、実行できません。

#+begin_src bash
$ sudo dpkg-reconfigure keyboard-configuration
Your console font configuration will be updated the next time your system
boots. If you want to update it now, run 'setupcon' from a virtual console.
#+end_src

* 参考

** 参考ページ
 - [[https://astherier.com/blog/2021/07/windows11-wsl2-wslg-japanese/#][Win11のWSL2 (WSLg)を日本語化 & Mozcで日本語入力 | AsTechLog]]
https://astherier.com/blog/2021/07/windows11-wsl2-wslg-japanese/

多くの内容に関して上記を参考にしました。

** xset -r の意味
 - [[https://netlog.jpn.org/r271-635/2021/08/windows10ver21h1_wsl2_gui_jp.html][Windows 10バージョン21H1でのWSL2のGUI日本語化 (r271-635)]]

上記より

#+begin_quote
xset -r は、キーのリピートを無効にするという意味合いで、全角・半角キーと重複するキーコード 49 『 ` 』が無駄にリピート入力されるバグを抑える働きをする。
#+end_quote

** gnome-session-properties

gnome-session-properties でスタートアップ設定ができるようです。

#+begin_src bash
$ sudo apt install gnome-startup-applications
#+end_src

#+begin_src bash
$ gnome-session-properties
#+end_src

# images/873_01.jpg http://cha.la.coocan.jp/wp/wp-content/uploads/2023/11/873_01-1.jpg
# images/873_02.jpg http://cha.la.coocan.jp/wp/wp-content/uploads/2023/11/873_02.jpg
# images/873_03.jpg http://cha.la.coocan.jp/wp/wp-content/uploads/2023/11/873_03.jpg
# images/873_04.jpg http://cha.la.coocan.jp/wp/wp-content/uploads/2023/11/873_04.jpg
# images/873_05.jpg http://cha.la.coocan.jp/wp/wp-content/uploads/2023/11/873_05.jpg

** その他の参考ページ
 - [[https://qiita.com/dozo/items/97ac6c80f4cd13b84558][fcitxで作るWSL日本語開発環境 #WSL - Qiita]]
 - [[https://kazblog.hateblo.jp/entry/2018/05/28/221242][Ubuntu18.04+WSLでfcitx-mozcを使って日本語入力出来るようにする - もやし日誌]]
 - [[https://notekunst.hatenablog.com/entry/fcitx-mozc][日本語入力の設定（fcitx + mozc） - Note to Self by notekunst]]
 - [[https://www.archlinux.site/2019/12/linux.html][Linuxでキーボードレイアウトが日本語配列にならない時の対処法 | 普段使いのArch Linux]]
 - [[https://kledgeb.blogspot.com/2022/05/ubuntu-2204-98.html#google_vignette][Ubuntu 22.04 その98 - 入力ソースとキーボートレイアウトと日本語入力のカスタマイズ - kledgeb]]
 - [[https://daiki-iijima.github.io/2021/03/11/%E3%80%90Ubuntu%E3%80%91%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89%E3%81%AE%E5%88%9D%E6%9C%9F%E8%A8%AD%E5%AE%9A/][【Ubuntu】キーボードの初期設定 - Inside the Black box .]]
 - [[https://www.aise.ics.saitama-u.ac.jp/~gotoh/TroubleShootingAboutUbuntu2004OnWSL2.html][トラブルシューティング（Ubuntu 20.04LTS on WSL2）]]
